Configurations:
  - OfficeOnlineServerSetup
  - OfficeOnlineServerFarmConfig

OfficeOnlineServerSetup:
  #Path: C:\OfficeOnline\Setup.exe
  Path: '[x= { $Datum.Global.SharePointSettings."$($Node.Environment)Path" } =]'
  LanguagePacks:
    - Language: de-de
      BinaryDir: C:\de-de
    - Language: en-us
      BinaryDir: C:\en-us
